# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master, development, '**-RC' ]
  workflow_dispatch:

permissions: {}

jobs:
  build:

    permissions:
      actions: write
      contents: write

    strategy:
      matrix:
        node-version: [24.x]
        runtime:
          - win-x64
        include:
        - runtime: win-x64
          os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: 'Use faster D: drive for yarn cache on Windows'
      if: startsWith(matrix.os, 'windows')
      shell: cmd
      run: yarn config set cache-folder D:\ft_yarn_cache

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: "yarn"
    - run: yarn run ci
      shell: bash
      env:
        ELECTRON_SKIP_BINARY_DOWNLOAD: '1'
    - run: yarn run lint
      shell: bash
    - name: Set version number
      id: versionNumber
      shell: bash
      run: |
        original_version="$(jq -r '.version' package.json)"
        version="$original_version"
        lower_case_ref="$(echo -E "$GITHUB_REF" | tr '[:upper:]' '[:lower:]')"
        if [[ "$lower_case_ref" == *development* ]]; then
          version="${original_version}-nightly-${GITHUB_RUN_NUMBER}"
        elif [[ "$lower_case_ref" == *rc* ]]; then
          version="${original_version}-RC-${GITHUB_RUN_NUMBER}"
        fi
        package_json="$(jq --arg version "$version" '.version = $version' package.json)"
        echo -E "$package_json" > package.json
        echo "version=${version}" >> "$GITHUB_OUTPUT"

    - name: Build x64 with Node.js ${{ matrix.node-version}}
      if: contains(matrix.runtime, 'x64')
      shell: bash
      run: yarn run build

    - name: Upload Windows x64 .exe Artifact
      uses: actions/upload-artifact@v6
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-setup-x64.exe
        path: build/freetube Setup ${{ steps.versionNumber.outputs.version }}.exe

    - name: Upload Windows x64 .exe Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/freetube Setup ${{ steps.versionNumber.outputs.version }}.exe
        asset_name: freetube-${{ steps.versionNumber.outputs.version }}-setup-x64.exe
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Windows x64 Portable Artifact
      uses: actions/upload-artifact@v6
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-win-x64-portable.exe
        path: build/freetube ${{ steps.versionNumber.outputs.version }}.exe

    - name: Upload Windows x64 portable Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/freetube ${{ steps.versionNumber.outputs.version }}.exe
        asset_name: freetube-${{ steps.versionNumber.outputs.version }}-portable-x64.exe
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Windows x64 .zip Artifact
      uses: actions/upload-artifact@v6
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-win-x64-portable.zip
        path: build/freetube-${{ steps.versionNumber.outputs.version }}-win.zip

    - name: Upload Windows x64 .zip Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/freetube-${{ steps.versionNumber.outputs.version }}-win.zip
        asset_name: freetube-${{ steps.versionNumber.outputs.version }}-win-x64-portable.zip
        tag: ${{ github.ref }}
        overwrite: true

    - name: Upload Windows x64 .7z Artifact
      uses: actions/upload-artifact@v6
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        name: freetube-${{ steps.versionNumber.outputs.version }}-win-x64-portable.7z
        path: build/freetube-${{ steps.versionNumber.outputs.version }}-win.7z

    - name: Upload Windows x64 .7z Release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/freetube-${{ steps.versionNumber.outputs.version }}-win.7z
        asset_name: freetube-${{ steps.versionNumber.outputs.version }}-win-x64-portable.7z
        tag: ${{ github.ref }}
        overwrite: true
